[package]

name = "freeimage-sys"
version = "0.0.1"
authors = [ "Hervé Drolon <drolon@infonie.fr>", Arturo Castro <me@arturocastro.net> ]
links = "freeimage"
build = "build.rs"

[lib]
name = "freeimage_sys"
path = "empty.rs"
